jango_learning/jango_learning/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import home, redirect




urlpatterns= [
    url(r'^admin/', admin.site.urls),
    url(r'^redirect/', redirect, name="redirect"),
    url(r'^$', home, name="home"),
    url(r'^web/', include('web.urls' ,namespace="web")),
    # url (r'^$',post_model , name="post_model"),
]

jango_learning/web/urls.py
from django.conf.urls import url
from django.contrib import admin
from .views import post_model , login , post_model_detail , post_model_create , post_model_delete

urlpatterns = [

        url(r'^create/$', post_model_create, name='create'),
        url(r'^$', post_model, name="post_model"),
        url(r'^login/', login, name='login'),
        url(r'^(?P<id>\d+)/$', post_model_detail, name='detail'),
        url(r'^(?P<id>\d+)/delete/$', post_model_delete, name='delete'),


]

jango_learning/web/templates/web/create_view.html
<!--<!DOCTYPE html>-->
<!--<html lang="en">-->
<!--<head>-->
    <!--<meta charset="UTF-8">-->
    <!--<title>create a view</title>-->
<!--</head>-->
<!--<body>-->
<!--<form method="get" >-->
    <!--{% block id %}-->
    <!--{% endblock %}-->
<!--<input type="submit" value="create">-->
    <!--</form>-->
<!--</body>-->
<!--</html>-->

    <h1>New post</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_ul}}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>

jango_learning/web/templates/web/delete_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>delete view</title>
</head>
<body>
<!--{% if messages %}-->
<!--<ul class="messages">-->
    <!--{% for message in messages %}-->
    <!--<li {% if message.tags %} class="{{message.tags }}" {% endif %}>{{message}}</li>-->
    <!--{% endfor %}-->

</ul>
{{ object.title}}
<form action="." method="POST">{% csrf_token%}
    are you sure ?
    <input type="submit" value="Confirm">
    <input type="submit" value="Nope">
    <a  style="position:relative;top:100px;" href="/web/{{object.id}}">cancel</a>
</form>
</body>
</html>

jango_learning/web/templates/web/index_list.html
<!-- <!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>welcome to jango site</title>
  </head>
  <body> -->
    <p>

      this is a learning site
    </p>
    {% for object in object_list %}
        <li>
            <a href="/web/{{object.id}}">{{object.title}}</a>
            <!--<a href='{% url "web:detail" id=object.id %}'>{{object.title}}</a>-->
            <!--<a href='{{object.get_absolute_url}}'>{{object.title}}</a>-->
        </li>
    {% endfor %}
  <!-- </body>
</html> -->

jango_learning/web/templates/web/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>login</title>
</head>
<body>
<p> login form </p>
</body>
</html>

jango_learning/web/templates/web/post_model_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>post model detail</title>
</head>
<body>
<p> {{object.title}}</p>
</body>
</html>